// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuckzkkxmgdldvsjbsmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Y2t6a2t4bWdkbGR2c2pic21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzM4ODUsImV4cCI6MjA3MzYwOTg4NX0.PeLzpPe21y0lda3XEIN7cxusxHBrMjONMP00-7WBHpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});